
services:
  mongodb:
    container_name: invoice-mongodb
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./volumes/mongo/mongo_datas:/data/db
      - ./volumes/mongo/mongo_entrypoint/:/docker-entrypoint-initdb.d/
    ports:
      - 27017:27017
    networks:
      - invoices_network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 180s
      timeout: 10s
      retries: 3
    restart: on-failure
    command: mongod --auth
    profiles:
      - database


  flask:
    container_name: invoice-api
    image: flask_invoices:latest
    build:
      context: ./src/flask                    
      dockerfile: Dockerfile
    environment:
      FLASK_HOST: 0.0.0.0
      FLASK_PORT: 5000
      DEBUG_MODE: True
      DEFAULT_LIMITER_LIMITS: "60 per minute"
      CURRENT_VERSION: "v1"
      FLASK_SECRET_APP_KEY: "faf1Fz1daf8Z8z191Z"
      HASH_ALGORITHM: "argon2"
      MONGO_HOST: invoice-mongodb
      MONGO_PORT: 27017
      MONGO_API_USERNAME: api
      MONGO_API_PASSWORD: api
    volumes:
      - ./src/flask/:/app
    ports:
      - 5000:5000
    entrypoint: ["python", "app.py"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 180s
      timeout: 10s
      retries: 3
    restart: on-failure
    networks:
      - invoices_network
    profiles:
      - api

  

  streamlit:
    container_name: invoice-streamlit
    image: invoice_streamlit:latest
    build:
      context: ./src/streamlit                    
      dockerfile: Dockerfile
    environment:
      FLASK_HOST: 0.0.0.0
      FLASK_PORT: 5000
    volumes:
      - ./flask:/app
    ports:  
      - 8501:8501
    entrypoint: ["python", "app.py"]
    healthcheck:
      test: ["executable", "arg"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: on-failure
    networks:
      - invoices_network
    profiles:
      - ui




networks:
  invoices_network:
    external: true