# Common env variables
x-common-environment:
  &common-env
  COMMON_VAR: 0.0.0
  ANOTHER_COMMON_VAR: TEST



services:
  mongodb:
    image: mongo:7.0
    env_file:
      - .env
    volumes:
      - ./mongo_datas:/data/db
    ports:
      - ${MONGO_PORT}:27017
    networks:
      - invoices_network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 180s
      timeout: 10s
      retries: 3
    restart: on-failure


  flask:
    image: flask_invoices:latest
    build:
      context: .                    
      dockerfile: Dockerfile
    depends_on:
    - mongodb
    env_file:
      - .env
    volumes:
      - ./flask:/app
    ports:
      - 5000:${FLASK_PORT}
    entrypoint: ["python", "app.py"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 180s
      timeout: 10s
      retries: 3
    restart: on-failure
    networks:
      - invoices_network

  
networks:
  invoices_network:
    external: true